export const adminsData = [
  {
    id: 1,
    name: "أحمد حمدي",
    email: "ahmed.hamdy@example.com",
    role: "المدير العام",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    phone: "01234567890",
    status: "نشط",
    lastLogin: "2024-07-21T10:00:00Z",
    permissions: [
      "إدارة المستخدمين",
      "إدارة المنتجات",
      "إدارة الطلبات",
      "عرض التقارير",
      "تغيير الإعدادات",
    ],
  },
  {
    id: 2,
    name: "فاطمة علي",
    email: "fatima.ali@example.com",
    role: "مدير المنتجات",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    phone: "01123456789",
    status: "غير نشط",
    lastLogin: "2024-07-20T15:30:00Z",
    permissions: ["إدارة المنتجات", "إدارة التصنيفات"],
  },
  {
    id: 3,
    name: "محمد حسن",
    email: "mohamed.hassan@example.com",
    role: "مدير الطلبات",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    phone: "01012345678",
    status: "نشط",
    lastLogin: "2024-07-21T09:00:00Z",
    permissions: ["إدارة الطلبات", "إدارة الفواتير"],
  },
  {
    id: 4,
    name: "سارة إبراهيم",
    email: "sara.ibrahim@example.com",
    role: "مشرف",
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
    phone: "01587654321",
    status: "نشط",
    lastLogin: "2024-07-21T11:00:00Z",
    permissions: ["إدارة المستخدمين", "عرض الطلبات"],
  },
]; 