export const bestSellingProducts = [
  {
    id: 1,
    name: "لابتوب ألعاب",
    image: "https://via.placeholder.com/40x40.png?text=Laptop",
    unitsSold: 120,
    salesContribution: 25.5,
    changePercentage: 15.2,
    totalProfit: 18000,
  },
  {
    id: 2,
    name: "سماعة رأس لاسلكية",
    image: "https://via.placeholder.com/40x40.png?text=Headphones",
    unitsSold: 350,
    salesContribution: 18.2,
    changePercentage: -5.8,
    totalProfit: 12000,
  },
  {
    id: 3,
    name: "كرسي مكتب مريح",
    image: "https://via.placeholder.com/40x40.png?text=Chair",
    unitsSold: 80,
    salesContribution: 15.0,
    changePercentage: 22.0,
    totalProfit: 9500,
  },
  {
    id: 4,
    name: "شاشة 4K",
    image: "https://via.placeholder.com/40x40.png?text=Monitor",
    unitsSold: 95,
    salesContribution: 12.8,
    changePercentage: 8.5,
    totalProfit: 11500,
  },
  {
    id: 5,
    name: "لوحة مفاتيح ميكانيكية",
    image: "https://via.placeholder.com/40x40.png?text=Keyboard",
    unitsSold: 250,
    salesContribution: 9.5,
    changePercentage: 30.1,
    totalProfit: 7500,
  },
]; 