export const topRatedUsers = [
  {
    id: 1,
    name: "محمد علي",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    totalSpent: 5400.75,
    lastPurchase: "2024-05-20",
    favoriteCategory: "الإلكترونيات",
    totalOrders: 25,
  },
  {
    id: 2,
    name: "فاطمة الزهراء",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    totalSpent: 4800.5,
    lastPurchase: "2024-05-18",
    favoriteCategory: "الملابس",
    totalOrders: 32,
  },
  {
    id: 3,
    name: "أحمد محمود",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    totalSpent: 4200.0,
    lastPurchase: "2024-05-21",
    favoriteCategory: "الأدوات المنزلية",
    totalOrders: 18,
  },
  {
    id: 4,
    name: "سارة إبراهيم",
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
    totalSpent: 3900.25,
    lastPurchase: "2024-05-15",
    favoriteCategory: "مستحضرات التجميل",
    totalOrders: 40,
  },
  {
    id: 5,
    name: "خالد عبد الله",
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
    totalSpent: 3500.0,
    lastPurchase: "2024-05-22",
    favoriteCategory: "الكتب",
    totalOrders: 15,
  },
]; 